Debug secrets

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -3,8 +3,42 @@ name: Docker Image CI
 on: [push, pull_request, workflow_dispatch]
 
 jobs:
+  preFlight:
+    name: "Preflight Checks"
+    runs-on: ubuntu-latest
+    steps:
+
+    - name: Assert Secrets Present
+      shell: bash
+      run: |
+        MD5() {
+          result=($(md5sum <(echo "${1}")))
+          echo $result
+        }
+
+        secretPresent() {
+          emptyHash=$(MD5 "")
+          secretHash=$(MD5 "${1}")
+          ! diff <(echo $secretHash) <(echo $emptyHash) &> /dev/null
+        }
+
+        errorMessage() {
+          echo "Your secret ${1} seems to be missing please contact the LedgerSMB team"
+          return 1
+        }
+
+        secretStatus=0
+
+        secretPresent "${{ secrets.GITHUB_TOKEN }}" || errorMessage "GITHUB_TOKEN" || secretStatus=1
+        secretPresent "${{ secrets.DOCKER_TOKEN }}" || errorMessage "DOCKER_TOKEN" || secretStatus=2
+
+        exit $secretStatus
+
+    - run: echo "Everything Checks Out 👍"
+
   repository:
     runs-on: ubuntu-latest
+    needs: preFlight
     outputs:
       hub: ${{ steps.docker_hub.outputs.hub }}
     steps:
